### ISSUE TITLE
v1.0 Milestone Planning

### ISSUE THREAD

**Issue by joshblack** [abbeyhrt/keep-up-old#1]
i.e., what can we get done by April 1st 😄  (2 months)

I think we'll end up having a `v0.5` Milestone that's in between now and the end of March just as a way to better reflect and see if we can hit our targets.

Overall structure might be that in the first month, the focus is on building out the functionality that we want to support. The second month is then a focus on polish, UI refinements, and bug squashing.

**Comment by joshblack** [comment]
cc @abbeyhrt

**Comment by abbeyhrt** [comment]
@joshblack So in the second month is when we would do the design too? and then polish that

**Comment by abbeyhrt** [comment]
As a roommate, i want to know when i need to vaccuum so that i am doing my fair share.
As a home-owner, i want to know when to schedule maintenance of my house so that i keep it in good repair.(this might be a stretch but essentially the idea is knowing when to do bigger tasks like cleaning gutters or power washing the drive) 
As head of the household, i want to be able to organize tasks between other occupants so that everyone knows what they need to do

**Comment by abbeyhrt** [comment]
As a child assigned tasks, i want to be able to mark each task as completed so my parents know when i completed them.

**Comment by abbeyhrt** [comment]
As a parent, i want to be able to add descriptions to tasks so that my children know how to complete each task

**Comment by abbeyhrt** [comment]
As a user, i can assign tasks to a room so i know where certain tasks need to be performed.

**Comment by joshblack** [comment]
- Features
  - Sign Up / Login / Logout / Authentication
  - Home
    - Create a home
    - Edit a home
    - Add rooms to home
    - Remove rooms from home
    - Add tasks to home
    - Remove tasks from home
  - Rooms
    - Edit a room
    - Delete a room
    - Add tasks to room
    - Remove tasks from room
  - Tasks
    - Edit a task
    - Remove a task
  - Settings
  - `/home`, Dashboard view
    - View your tasks
  - Reminders
    - Remind of upcoming task with push notifications

---

TODO:

- Domain modeling
  - Create initial GraphQL schema
- Backend
  - Design routes for RESTful API
  - Implement each route
  - GraphQL
- Design
- UI
