### ISSUE TITLE
Plan and write an article 

### ISSUE THREAD

**Issue by abbeyhrt** [abbeyhrt/keep-up-old#19]
Ideas:
How to use ApolloClient with graphql. 
Beginner's Guide to GraphQL
Intro to CRUD
HOC vs Render Prop article

**Comment by joshblack** [comment]
Issue moved to [abbeyhrt/keep-up #14](https://github.com/abbeyhrt/keep-up/issues/14) via [**ZenHub**](https://www.zenhub.com/)
